apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: calcapp
spec:
  template:
    spec:
      containers:
        - image: ankitraut0987/calc-app:1.0.0
          ports:
            - name: contport
              containerPort: 8000
